doc-warnings: true
test-warnings: true
strictness: high
max-line-length: 79
pylint:
  disable:
    - exec-used
pyroma:
  - run: true
ignore-paths:
 - docs
ignore-patterns:
 - (^|/)__init__\.py
 - pyautoupdate/.+commonpath.py
python-targets:
 - 2
 - 3
