author_approval: required
approve_by_comment: true
approve_regex: ^Pull[Aa]pprove [Aa]pproval signified
author_approval: default
reject_regex: ^Pull[Aa]pprove [Rr]ejection signified
reset_on_push: true
reset_on_reopen: true
reviewers:
  members:
  - rlee287
  name: owner
  required: 1
